---
version: "3.9"
services:
  gatus:
    image: twinproduction/gatus:v5.7.0
    ports:
      - "8081:8080"
    volumes:
      - /docker/docker-compose/gatus/config:/config
      - /docker/docker-compose/gatus/data:/data/
    restart: unless-stopped